development:
  sessions:
    default:
      database: furl_manager_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: furl_manager_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
