development:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost/short_url_manager_development" %>
test:
  clients:
    default:
      uri: <%= ENV["TEST_MONGODB_URI"] || "mongodb://localhost/short_url_manager_test" %>
production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
