development:
  host: 127.0.0.1
  port: 6379
  namespace: short-url-manager
test:
  host: 127.0.0.1
  port: 6379
  namespace: short-url-manager
production:
  host: <%= ENV["REDIS_HOST"] %>
  port: <%= ENV["REDIS_PORT"] %>
  namespace: short-url-manager
